In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("transform price - Sheet1 (1).csv")
df.head(9)

price
0    110
1    105
2    115
3    120
4    110
5    130
6    150
7    100
8    105

In [3]:
original_array = np.array([110., 105., 115., 120., 110., 130., 150., 100., 105.])
data = original_array.reshape(1, -1)
data

array([[110., 105., 115., 120., 110., 130., 150., 100., 105.]])

# Normalization

In [4]:
from sklearn.preprocessing import MinMaxScaler


In [5]:
m = MinMaxScaler()

In [23]:
df_price = m.fit(data)
df_price

MinMaxScaler()

In [7]:
data.min()

100.0

In [8]:
data.max()

150.0

In [9]:
Xnew= (data - data.min())/(data.max()-data.min())
Xnew

array([[0.2, 0.1, 0.3, 0.4, 0.2, 0.6, 1. , 0. , 0.1]])

In [24]:
df_price = m.transform(data)
df_price

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# Standardization

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
n = StandardScaler()

In [17]:
df_price = n.fit(data)
df_price

StandardScaler()

In [18]:
data.std()

14.677605348469895

In [19]:
data.mean()

116.11111111111111

In [21]:
X1new = (data - data.mean())/data.std()
X1new

array([[-0.41635614, -0.75701116, -0.07570112,  0.26495391, -0.41635614,
         0.94626396,  2.30888405, -1.09766619, -0.75701116]])

# RobustScaler

In [30]:
from sklearn.preprocessing import RobustScaler

In [31]:
p = RobustScaler()  

In [32]:
q1 = np.percentile(data, 25)
q3 = np.percentile(data, 75)
iqr = q3 - q1

In [33]:
print("Interquartile Range:", iqr)

Interquartile Range: 15.0


In [34]:
median = np.median(data)
print("The median is:", median)

The median is: 110.0


In [35]:
Xscale = (data - median)/ iqr
Xscale

array([[ 0.        , -0.33333333,  0.33333333,  0.66666667,  0.        ,
         1.33333333,  2.66666667, -0.66666667, -0.33333333]])

In [36]:
df_price = p.fit_transform(data)
df_price

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# Max Abs

In [37]:
from sklearn.preprocessing import MaxAbsScaler


In [38]:
s = MaxAbsScaler()

In [39]:
data.max()

150.0

In [40]:
data

array([[110., 105., 115., 120., 110., 130., 150., 100., 105.]])

In [41]:
xscaled= data/data.max()
xscaled

array([[0.73333333, 0.7       , 0.76666667, 0.8       , 0.73333333,
        0.86666667, 1.        , 0.66666667, 0.7       ]])

In [42]:
df_price = s.fit_transform(data)
df_price

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# Log transformer

In [43]:
 from sklearn.preprocessing import FunctionTransformer


In [44]:
transformer = FunctionTransformer(np.log1p)


In [48]:
 X =  np.array([data])
   
    

In [46]:
transformer.transform(X)

array([[[4.7095302 , 4.66343909, 4.75359019, 4.79579055, 4.7095302 ,
         4.87519732, 5.01727984, 4.61512052, 4.66343909]]])