# Part 1: Data Preprocessing

1. Load the Excel dataset into a pandas DataFrame. Handle any missing values and perform data 
exploration to understand the characteristics of the dataset.

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
df = pd.read_csv("Real estate - Real estate.csv")

In [7]:
df.head()

No  X1 transaction date  X2 house age  \
0   1             2012.917          32.0   
1   2             2012.917          19.5   
2   3             2013.583          13.3   
3   4             2013.500          13.3   
4   5             2012.833           5.0   

   X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                84.87882                               10   
1                               306.59470                                9   
2                               561.98450                                5   
3                               561.98450                                5   
4                               390.56840                                5   

   X5 latitude  X6 longitude  Y house price of unit area  
0     24.98298     121.54024                        37.9  
1     24.98034     121.53951                        42.2  
2     24.98746     121.54391                        47.3  
3     24.98746     121.54391                        54.8  
4     24.97937     121.54245                        43.1

In [8]:
df.shape

(414, 8)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 8 columns):
 #   Column                                  Non-Null Count  Dtype  
---  ------                                  --------------  -----  
 0   No                                      414 non-null    int64  
 1   X1 transaction date                     414 non-null    float64
 2   X2 house age                            414 non-null    float64
 3   X3 distance to the nearest MRT station  414 non-null    float64
 4   X4 number of convenience stores         414 non-null    int64  
 5   X5 latitude                             414 non-null    float64
 6   X6 longitude                            414 non-null    float64
 7   Y house price of unit area              414 non-null    float64
dtypes: float64(6), int64(2)
memory usage: 26.0 KB


In [10]:
df.describe() # Provides statistics like mean, standard deviation, min, max, quartiles, etc. for numeric columns.

No  X1 transaction date  X2 house age  \
count  414.000000           414.000000    414.000000   
mean   207.500000          2013.148971     17.712560   
std    119.655756             0.281967     11.392485   
min      1.000000          2012.667000      0.000000   
25%    104.250000          2012.917000      9.025000   
50%    207.500000          2013.167000     16.100000   
75%    310.750000          2013.417000     28.150000   
max    414.000000          2013.583000     43.800000   

       X3 distance to the nearest MRT station  \
count                              414.000000   
mean                              1083.885689   
std                               1262.109595   
min                                 23.382840   
25%                                289.324800   
50%                                492.231300   
75%                               1454.279000   
max                               6488.021000   

       X4 number of convenience stores  X5 latitude  X6 longitude  \
count                       414.000000   414.000000    414.000000   
mean                          4.094203    24.969030    121.533361   
std                           2.945562     0.012410      0.015347   
min                           0.000000    24.932070    121.473530   
25%                           1.000000    24.963000    121.528085   
50%                           4.000000    24.971100    121.538630   
75%                           6.000000    24.977455    121.543305   
max                          10.000000    25.014590    121.566270   

       Y house price of unit area  
count                  414.000000  
mean                    37.980193  
std                     13.606488  
min                      7.600000  
25%                     27.700000  
50%                     38.450000  
75%                     46.600000  
max                    117.500000

In [11]:
df.isna().sum() # Count missing values in each column.

No                                        0
X1 transaction date                       0
X2 house age                              0
X3 distance to the nearest MRT station    0
X4 number of convenience stores           0
X5 latitude                               0
X6 longitude                              0
Y house price of unit area                0
dtype: int64

In [12]:
df = df.rename(columns = {'X1 transaction date':'trans.date', 'X2 house age':'h.age','X3 distance to the nearest MRT station':'mrt','X4 number of convenience stores':'con.stores', 'X5 latitude':'latitude','X6 longitude':'longitude','Y house price of unit area':'price'}
)
df.head()

No  trans.date  h.age        mrt  con.stores  latitude  longitude  price
0   1    2012.917   32.0   84.87882          10  24.98298  121.54024   37.9
1   2    2012.917   19.5  306.59470           9  24.98034  121.53951   42.2
2   3    2013.583   13.3  561.98450           5  24.98746  121.54391   47.3
3   4    2013.500   13.3  561.98450           5  24.98746  121.54391   54.8
4   5    2012.833    5.0  390.56840           5  24.97937  121.54245   43.1

2. Extract the feature columns (X1 to X6) and the target column (Y). Split the dataset into features (X) and 
target (y). (70% training & 30% testing ratio).


In [13]:
X =df.drop('price', axis=1)
X.head() #splite data set into (X),(Y)


No  trans.date  h.age        mrt  con.stores  latitude  longitude
0   1    2012.917   32.0   84.87882          10  24.98298  121.54024
1   2    2012.917   19.5  306.59470           9  24.98034  121.53951
2   3    2013.583   13.3  561.98450           5  24.98746  121.54391
3   4    2013.500   13.3  561.98450           5  24.98746  121.54391
4   5    2012.833    5.0  390.56840           5  24.97937  121.54245

In [14]:
Y = df['price']
Y.head()

0    37.9
1    42.2
2    47.3
3    54.8
4    43.1
Name: price, dtype: float64

In [15]:
from sklearn.model_selection import train_test_split
train, test=train_test_split(df, test_size=.30)
train.head()


No  trans.date  h.age         mrt  con.stores  latitude  longitude  \
135  136    2012.917   18.9  1009.23500           0  24.96357  121.54951   
348  349    2012.833    4.6   259.66070           6  24.97585  121.54516   
408  409    2013.417   18.5  2175.74400           3  24.96330  121.51243   
37    38    2013.167   12.0  1360.13900           1  24.95204  121.54842   
172  173    2013.583    6.6    90.45606           9  24.97433  121.54310   

     price  
135   20.8  
348   53.7  
408   28.1  
37    25.3  
172   58.1

In [16]:
Xtrain, Xtest,Ytrain, Ytest = train_test_split(X, Y, test_size=.30, random_state=42)

In [17]:
Xtrain.head()

No  trans.date  h.age         mrt  con.stores  latitude  longitude
7      8    2013.417   20.3   287.60250           6  24.98042  121.54228
194  195    2013.500   15.2  3771.89500           0  24.93363  121.51158
19    20    2012.667    1.5    23.38284           7  24.96772  121.54102
176  177    2012.833   13.9  4573.77900           0  24.94867  121.49507
367  368    2012.833   15.0  1828.31900           2  24.96464  121.51531

In [18]:
Ytrain.head()

7      46.7
194    29.3
19     47.7
176    19.2
367    20.9
Name: price, dtype: float64

In [19]:
Xtest.head()

No  trans.date  h.age        mrt  con.stores  latitude  longitude
358  359    2013.167    1.1   193.5845           6  24.96571  121.54089
350  351    2013.000   13.2   492.2313           5  24.96515  121.53737
373  374    2013.083    0.0   274.0144           1  24.97480  121.53059
399  400    2012.917   12.7   170.1289           1  24.97371  121.52984
369  370    2012.667   20.2  2185.1280           3  24.96322  121.51237

In [20]:
Ytrain.shape

(289,)

In [21]:
Ytest.head()

358    45.1
350    42.3
373    52.2
399    37.3
369    22.8
Name: price, dtype: float64

In [22]:
Ytest.shape

(125,)

3. Standardize the feature columns (X1 to X6) using Z-score scaling. Implement the scaling process 
manually (without using libraries like `scikit-learn`)

In [23]:
columns_to_standardize = ['trans.date', 'h.age', 'mrt', 'con.stores', 'latitude', 'longitude']

In [24]:
mean_values = {}
std_values = {}


In [25]:
for col in columns_to_standardize:
    mean_values[col] = X[['trans.date', 'h.age', 'mrt', 'con.stores', 'latitude', 'longitude']].mean()
    
    std_values[col] = X[['trans.date', 'h.age', 'mrt', 'con.stores', 'latitude', 'longitude']].std()

In [26]:
print("Mean:", mean_values[col])

print("\nstd:", std_values[col])

Mean: trans.date    2013.148971
h.age           17.712560
mrt           1083.885689
con.stores       4.094203
latitude        24.969030
longitude      121.533361
dtype: float64

std: trans.date       0.281967
h.age           11.392485
mrt           1262.109595
con.stores       2.945562
latitude         0.012410
longitude        0.015347
dtype: float64


In [27]:
scaled_X = X.copy()
for col in columns_to_standardize:
    scaled_X = (X[['trans.date', 'h.age', 'mrt', 'con.stores', 'latitude', 'longitude']] - mean_values[col]) / std_values[col]

In [28]:
scaled_X

trans.date     h.age       mrt  con.stores  latitude  longitude
0     -0.822688  1.254111 -0.791537    2.004982  1.124070   0.448220
1     -0.822688  0.156896 -0.615866    1.665488  0.911342   0.400654
2      1.539289 -0.387322 -0.413515    0.307513  1.485063   0.687352
3      1.244928 -0.387322 -0.413515    0.307513  1.485063   0.687352
4     -1.120595 -1.115873 -0.549332    0.307513  0.833180   0.592220
..          ...       ...       ...         ...       ...        ...
409   -0.528327 -0.352211  2.375490   -1.389957 -2.214314  -1.925506
410   -1.709316 -1.063206 -0.787118    1.665488  0.427062   0.634573
411    0.358300  0.095452 -0.549014    0.986500  0.821899   0.423460
412   -0.528327 -0.843763 -0.775745    0.307513 -0.184532   0.476238
413    1.244928 -0.984207 -0.787118    1.665488  0.427062   0.634573

[414 rows x 6 columns]

# Part 2: Linear Regression

4. Implement a simple linear regression model using the scaled features (X1 to X6) to predict the house 
price (Y). You can use gradient descent for optimization. Calculate the regression coefficients (intercept 
and slope) and write down the regression equation.

In [29]:
X.head(289)

No  trans.date  h.age        mrt  con.stores  latitude  longitude
0      1    2012.917   32.0   84.87882          10  24.98298  121.54024
1      2    2012.917   19.5  306.59470           9  24.98034  121.53951
2      3    2013.583   13.3  561.98450           5  24.98746  121.54391
3      4    2013.500   13.3  561.98450           5  24.98746  121.54391
4      5    2012.833    5.0  390.56840           5  24.97937  121.54245
..   ...         ...    ...        ...         ...       ...        ...
284  285    2012.917   15.0  383.28050           7  24.96735  121.54464
285  286    2013.167   30.1  718.29370           3  24.97509  121.53644
286  287    2012.917    5.9   90.45606           9  24.97433  121.54310
287  288    2013.000   19.2  461.10160           5  24.95425  121.53990
288  289    2013.583   16.6  323.69120           6  24.97841  121.54280

[289 rows x 7 columns]

In [30]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()

In [31]:
Reg = reg.fit(X, Y)
Reg


LinearRegression()

In [32]:
reg.coef_

array([-3.59350128e-03,  5.07908732e+00, -2.70841959e-01, -4.52079011e-03,
        1.12927749e+00,  2.24672892e+02, -1.44235635e+01])

In [33]:
reg.intercept_

-14038.079782924147

In [44]:

Y =((reg.coef_)*32)+(reg.intercept_)

Y

array([-14038.19477497, -13875.5489888 , -14046.74672562, -14038.22444821,
       -14001.94290335,  -6848.54723162, -14499.63381372])

5. Evaluate the model's performance using metrics such as Mean Squared Error (MSE) and R-squared. 
Interpret the R-squared value in the context of this regression

In [50]:
Ypred= reg.predict(Xtest)
Ypred

array([47.34924152, 40.69815138, 43.34746698, 39.20678333, 27.05782984,
       45.50794239, 44.4831901 , 46.53168074, 24.0437536 , 54.76629818,
       34.13415415, 36.64381765, 37.02784194, 23.86067762, 35.51336144,
       33.53919606, 43.89609878, 45.21625484, 29.59936196, 44.70150697,
        1.57339504, 35.48386229, 47.57541992, 45.68405197, 11.63335437,
       38.72953552, 12.98787983, 43.09465602, 35.37848586, 37.38882862,
       13.89809241, 40.12197202, 35.85292458, 28.52317152, 47.00535857,
       30.67741002, 50.79701913, 13.65744228, 48.94114972, 39.59771905,
       38.73649247, 40.19083191, 47.89494828, 37.24834958, 39.76284104,
       47.36421647, 43.77049754, 21.89289591, 47.3480626 , 45.08158447,
       48.24874144, 48.41881747, 41.63881627, 42.38683218, 36.07425087,
       15.6859821 , 37.12270337, 35.33420969, 28.86900812, 46.47306013,
       32.47335135, 32.63559946, 15.39131499,  9.33256004, 10.04209091,
       33.73920908, 29.50341213, 47.30437819, 33.30751556, 31.88

In [47]:
from sklearn.metrics import mean_squared_error

MSE = mean_squared_error(Ytest, Ytrain)
MSE

ValueError: Found input variables with inconsistent numbers of samples: [414, 289]

In [48]:
from sklearn.metrics import r2_score
r2 = r2_score(Ytest, Ypred)
print("R-squared:", r2)


ValueError: Found input variables with inconsistent numbers of samples: [414, 125]